services:
  - type: web
    name: kz-arena
    env: python
    region: frankfurt
    plan: starter
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn kz_arena.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 120
    autoDeploy: true
    disk:
      name: kz-arena-media
      mountPath: /opt/render/project/src/media
      sizeGB: 2
    envVars:
      - key: ENV_NAME
        value: prod
      - key: DEBUG
        value: "0"
      - key: USE_HTTPS
        value: "1"
      - key: SECURE_SSL_REDIRECT
        value: "1"
      - key: SERVE_MEDIA
        value: "1"
      - key: LOG_LEVEL
        value: INFO
      - key: PRIMARY_DOMAIN
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DB_ENGINE
        value: postgres
      - key: DB_HOST
        fromDatabase:
          name: kz-arena-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: kz-arena-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: kz-arena-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: kz-arena-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: kz-arena-db
          property: password

databases:
  - name: kz-arena-db
    databaseName: kz_arena
    user: kz_arena
    plan: basic-256mb
    region: frankfurt
